
# The name of your website.
name: avoinrajapinta.fi

description:

  # Description of your site. This will show up in google.
  meta: Avoimen rajapinnan (API) käsitteen määritelmä, periaatteet suunnitteluun.

  # Description of your site. This will show up on the front page.
  subtitle: Avoimen rajapinnan määritelmä, periaatteet suunnitteluun.

author:
  name: Open Knowledge Finland & COSS

  # Necessary for contact page
  email: mika.honkanen@okf.fi
  phone_number: +358-50-4116-720

  # Optional text (html) to display after author name. Leave empty if you don't
  # want it.
  info:


# The URL of the homepage of your site (without trailing slash).
# Leave this empty when you run Jekyll locally.
#url: # Empty url is needed when testing on localhost, but should be disabled before publishing
url: http://avoinrajapinta.fi

# Base URL is only needed if site is in a sub-directory
baseurl: ""

# language attribute in <html> element.
lang: fi
country_name: Finland

# FROM THIS POINT ON EVERYTHING IS OPTIONAL

##############
# APPEREANCE #
##############

# If you want to show the subtitle anywhere else than the front page, use
# {% include subtitle.html %} to include it anywhere you want.
show-subtitle: false
display-social-icons: true

footer-text: This is the footer.<br><a href="http://steinvc.github.io/holo-alfa/">Holo Alfa</a>.

# Preferably 64px in height. Leave empty = disable.
logo-image: "/img/logo/avoinrajapinta-logo@0.5x.png"

# Toolbar color for Chrome on Android.
theme-color-attr: "#00f0ff"

# Color of Microsoft live Tile.
ms-tile-color: "#00f0ff"

# Color used throughout the theme. Format: R, G, B.
theme-color: 216, 216, 216
# Original: 0, 240, 255

# Text color used throughout the theme. Format: R, G, B.
text-color: 0, 0, 0
# Original: 0, 0, 0

# Background color used throughout the theme. Format: R, G, B.
# Note: if you change the background color AND you use cover images, you should
#       also change the CSS gradient in "_includes\gradient.css" to match the
#       background color. Edit and copy it from here:
#       http://www.colorzilla.com/gradient-editor/#ffffff+0,ffffff+100&0+0,1+100
background-color: 255, 255, 255 # Original: 255, 255, 255

display-author-post-page: true
display-author-front-page: true

# http://alanwsmith.com/jekyll-liquid-date-formatting-examples
date_format: "%b %-d, %Y"

# Minimal screen-width after which the navigation will change position from
# vertical to horizontal.
nav-breaking-point: 520px

# Number of posts on each page.
paginate: 3

# Display links for the previous and next post on post pages.
display-next-prev-post: false

# Leave empty if you don't want comments on post pages.
disqus-shortname:


################
# SOCIAL ICONS #
################

# Use a complete url here, including http:// and such. Requiring just usernames
# has been considered, but this is way more customizable.
twitter:
youtube:
instagram:
tumblr:
facebook: https://www.facebook.com/groups/apisuomi/
google-plus:
reddit:
soundcloud:
medium:
linkedin:
github: https://github.com/okffi/open-api-definition/
behance:
codepen:
dribbble:
trello:
stack-overflow:
bitcoin:
paypal:


#####################
# CUSTOMIZABLE TEXT #
#####################

# Useful for translating into other languages.

var_on_the_web: On the web
var_read: Lue # Text after each post summary on the homepage.
var_newer: Uudempi
var_older: Vanhempi
var_next_post: Seuraava
var_previous_post: Edellinen
var_less_than_a_minute_read: Alle minuutti
var_min_read: minuuttia # Text after reading time. Example: 5 min read.
var_post_by: Kirjoittaneet
var_guest_post_by: Guest post by
var_your_email: Sähköposti
var_your_message: Viesti


##################
# BUILD SETTINGS #
##################

# You don't have to change these.

exclude: [vendor]
highlighter: rouge
kramdown:
  input: GFM
paginate_path: "/page-:num/"
permalink: pretty
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      excerpt_separator: "<!--more-->"


# Conversion
lsi:         false
incremental: false

# Filtering Content
show_drafts: null
limit_posts: 0
future:      false
unpublished: false

# Plugins
whitelist: []
gems:      [jekyll-paginate]
